version: '3.3'

services:
  pgadmin:
    container_name: docker-pgadmin-${BRANCH}
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  # set this to your email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # set this to your password
    volumes:
      - ${BRANCH}-data:/root/.pgadmin
    ports:
      - "5050:80"
    restart: always

volumes:
  ${BRANCH}-data: