version: '3.3'

services:
  pgadmin:
    container_name: docker-pgadmin-${BRANCH}
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  # set this to your email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # set this to your password
    volumes:
      - ${BRANCH}-data:/root/.pgadmin
    ports:
      - "${EXTERNAL_PORT}:80"
    restart: always
    networks:
      - $NETWORK
volumes:
  ${BRANCH}-data:

networks:
  $NETWORK:
     external: true